const translationTableExact = {
    // Main
    '天鳳 / Web版': 'Tenhou / Web version',
    '【イベント告知】': '<Event Notice>',
    'お試しゲストログイン': 'Guest Login',
    '新規ID登録': 'New ID',
    'IDで続きから': 'Existing ID',
    '【入力方法の調整を行っています】': 'Input method has been successfully changed',
    '希望の入力方法ではない場合には': 'If your desired input method is not chosen, ',
    '「設定」から変更をお願いいたします。': 'you can change it via settings.',
    '新規ID': 'New ID',
    'フリテン': 'Furiten',
    '男': 'Male',
    '女': 'Female',
    'ID変更': 'Change ID',
    '設定': 'Settings',
    'ロビーの移動': 'Change lobby',
    'ツモ': 'Tsumo',
    'ロン': 'Ron',
    'リーチ': 'Riichi',
    '拔き': 'Nuki',
    '流局': 'Redeal',
    'カン': 'Kan',
    '終了': 'Quit',
    '視 ': 'View pt. ',
    '局 ': 'Round ',
    '巡 ': 'Turn ',
    'ランキング戦': 'Ranked Play',
    '(段位戦、雀荘戦)': '(Ranked, Parlor)',
    'イベント会場１': 'Event Venue 1',
    '(公式イベントで使用します)': '(Official events)',
    'イベント会場２': 'Event Venue 2',
    'その他': 'Others',
    '(個室番号を指定してロビーを移動します)': '(Go to a private lobby)',
    'ロビーの新規作成': 'Create lobby',
    '(天鳳サイトの個室作成ページを開きます)': '(Link to the lobby creation page)',
    'このプレーヤは既に接続済みです。しばらく経ってから接続してください。(ERR1004)': 'This account is already logged in. Please try again later. (ERR1004)',
    '再接続しますか？': 'Reconnect?',
    'Wi-Fi(無線LAN)やbluetoothは電子レンジや近隣利用者の影響を受け接続が切れる場合があります': 'The connection may be broken due to inteference of microwave ovens or neighboring users',
    '入力してあるIDをクリアしますがよろしいですか？IDを紛失しないようにコピーしてください。': 'Clear the login ID field? Please consider keeping a copy of the ID to avoid losing it',
    // Settings
    '環境': 'Environment',
    ' / 設定': ' / Settings',
    '画面方向:回転': 'Screen orientation:Rotate',
    '画面方向:Default': 'Screen orientation:Default',
    '※アプリ版でのみご利用いただけます': '※Only applicable in App version',
    '配信ID保護': 'ID protection for live stream',
    '※ログイン画面のID入力を非表示にします': '※Makes your ID hidden on the login page',
    '入力補助:Default': 'Input Assist: Default',
    '入力補助:3TAP': 'Input Assist: 3TAP',
    '入力補助:2TAP': 'Input Assist: 2TAP',
    '※縦画面のみで表示されます': '※Only displayed when in portrait view',
    '牌山表示:Default': 'Show Wall:Default',
    '牌山表示:あり': 'Show Wall:On',
    '牌山表示:なし': 'Show Wall:Off',
    'SEなし': 'No SE',
    '卓': 'Table',
    '標準の画像': 'Use default BG image',
    '画像URL:': 'Image URL:',
    '牌': 'Tile',
    '牌背色:': 'Tile Colour',
    // Lobby
    '●アドレスバーを小さくするには下にスクロールしてからゆっくり上にスクロールします(機種依存あり)●OK/パス/ツモ切りは右クリックまたはダブルタップ': 'To make the address bar smaller, scroll down, then slowly scroll up (depends on the device). Right click or double tap to trigger Confirm / Pass / Auto Discard.',
    '※下の«»でタブを移動してください。': 'Use the «» buttons below to navigate',
    '接続:': 'Online:',
    '待機:': 'Idle:',
    '終局:': 'Last:',
    '有効期限:': 'Expire: ',
    '段級位を取得するには': 'Please register an ID in order',
    '「新規ID」登録が必要です': 'to be qualified for rankings',
    'テストプレイ': 'Test Play',
    '対戦': 'Play',
    '予約': 'Queue',
    '1位': '1st',
    '2位': '2nd',
    '3位': '3rd',
    '4位': '4th',
    '四麻:': '4P',
    '三麻:': '3P',
    '東風+4局サドンデス': 'east + 4 rounds of sudden death',
    '東南+4局サドンデス': 'east south + 4 rounds of sudden death',
    'ウマ': 'Uma',
    '1本場': 'Honba',
    '後': 'after',
    '明槓ドラ': 'Mindora',
    '喰断': 'Kuitan',
    '東西場': 'Tonshaba',
    '和了止め': 'Agariyame',
    '聴牌止め': 'Tenpaiyame',
    '月間戦績': 'Monthly Stats',
    '通算': 'Raw',
    '得点': 'Points',
    '順位': 'Placement',
    '収支': 'Income',
    '祝儀': 'Shuugi',
    '平均': 'Average',
    'トップ': 'Top rt',
    '連対率': 'Rentai',
    'ラス率': 'Last rt',
    '総合': 'Total',
    '対戦数': '# of games',
    '※段位戦４人打ち合算戦績': '※Summary of ranked 4P games',
    '※段位戦３人打ち合算戦績': '※Summary of ranked 3P games',
    '※表示する対戦ルールを選択してください': 'Choose a game type to display its stats',
    '通算戦績': 'Raw Stats',
    '１位率': '1st rt',
    '２位率': '2nd rt',
    '３位率': '3rd rt',
    '４位率': '4th rt',
    '飛び率': 'Bust rt',
    '平均得点': 'Avg points',
    '平均順位': 'Avg placing',
    '平均収支': 'Avg income',
    '平均祝儀': 'Avg shuugi',
    '和了率': 'Win rt',
    '放銃率': 'Deal-in rt',
    '副露率': 'Call rt',
    '立直率': 'Riichi rt',
    '牌譜': 'Replay',
    '牌譜 | ': 'Replay | ',
    '観戦': 'Spectate',
    '観戦 | ': 'Watch | ',
    'ヘルプ': 'Help',
    '牌理': 'Analyser',
    '料金のお支払い': 'Pay membership fee',
    '牌譜/観戦URLを入力してください': 'Enter URL of replay or live game',
    'ログイン画面の「新規ID」からIDを取得してください': 'Please first register an ID from the login page',
    '●「長押し」または「右クリック」から別タブで開く/URLのコピーなどが行えます': 'Long press or right click to bring up the context menu.',
    '●「長押し」または「右クリック」から別タブで開く/URLのコピーなどが行えます●観戦は５分遅れ': 'Long press or right click to bring up the context menu. Games are delayed five minutes in spectating mode.',
    '観戦可能な対戦はありません': 'There are no matches that can be watched.',
    '画像や音声がロードされていて正常に描画/再生可能かを確認するための機能です。もし異常があればゲームの進行に支障が出る場合がありますので、このページをリロードしてください。': 'You may use this feature to test whether image and sound files can be properly loaded. If there exists any abnormality which may hinder the progress of the game, please refresh this page.',
    '上級卓の入場条件(１級以上または有効期限60日以上)を満たしていません※七段R2000以上は入場できません': 'Must be at least 1 Kyuu to enter Joukyuu (Intermediate). ※Not available after 7 Dan & R2000',
    '特上卓の入場条件(四段R1800以上を満たしていません': 'Must be at least 4 Dan & R1800 to enter Tokujou (Expert).',
    '雀荘戦の入場条件(四段R1800以上の有料会員)を満たしていません': 'Must be at least 4 Dan & R1800 to enter Janso (Parlor). Not available to free players.',
    '鳳凰卓の入場条件(七段R2000以上の有料会員)を満たしていません': 'Must be at least 7 Dan & R2000 to enter Houou (Master). Not available to free players.',
    // Game
    '對局': 'Start',
    '鳴きなし': 'No call',
    '自動理牌': 'Sort',
    '不聴宣言': 'Noten',
    '自動和了': 'Auto ron',
    'ツモ切り': 'Auto discard',
    'ポン': 'Pon',
    'チー': 'Chii',
    '槓': 'Kan',
    'キタ': 'Kita',
    '終局': 'End',
    '飜': 'Han',
    '符': 'Fu',
    '点': 'Points',
    // Yaku
    '門前清自摸和': 'Menzen tsumo',
    '立直': 'Riichi',
    '一發': 'Ippatsu',
    '槍槓': 'Chankan',
    '嶺上開花': 'Rinshan kaihou',
    '海底摸月': 'Haitei raoyue',
    '河底撈魚': 'Houtei raoyui',
    '平和': 'Pinfu',
    '斷么九': 'Tanyao',
    '一盃口': 'Iipeikou',
    '自風 東': 'Jikaze Ton',
    '自風 南': 'Jikaze Nan',
    '自風 西': 'Jikaze Sha',
    '自風 北': 'Jikaze Pei',
    '場風 東': 'Bakaze Ton',
    '場風 南': 'Bakaze Nan',
    '場風 西': 'Bakaze Sha',
    '場風 北': 'Bakaze Pei',
    '役牌 白': 'Yakuhai Haku',
    '役牌 發': 'Yakuhai Hatsu',
    '役牌 中': 'Yakuhai Chun',
    '兩立直': 'W riichi',
    '七對子': 'Chiitoitsu',
    '混全帶么九': 'Chanta',
    '一氣通貫': 'Ikkitsuukan',
    '三色同順': 'Sanshoku doujun',
    '三色同刻': 'Sanshoku doukou',
    '三槓子': 'Sankantsu',
    '對對和': 'Toitoi',
    '三暗刻': 'Sanankou',
    '小三元': 'Shousangen',
    '混老頭': 'Honroutou',
    '二盃口': 'Ryanpeikou',
    '純全帶么九': 'Junchan',
    '混一色': 'Honitsu',
    '清一色': 'Chiniisou',
    '人和': 'Renhou',
    '天和': 'Tenhou',
    '地和': 'Chiihou',
    '大三元': 'Daisangen',
    '四暗刻': 'Suuankou',
    '四暗刻單騎': 'Suuankou tanki',
    '字一色': 'Tsuuiisou',
    '綠一色': 'Ryuuiisou',
    '清老頭': 'Chinroutou',
    '九蓮寶燈': 'Chuuren poutou',
    '純正九蓮寶燈': 'Junsei chuuren poutou',
    '國士無雙': 'Kokushi musou',
    '國士無雙13面': 'Kokushi musou 13 men',
    '大四喜': 'Daisuushi',
    '小四喜': 'Shousuushi',
    '四槓子': 'Suukantsu',
    'ドラ': 'Dora',
    '裏ドラ': 'Uradora',
    '赤ドラ': 'Akadora',
    // Replay & Spectating
    '待ち': 'Waits',
    '手牌': 'Hand',
    '牌山': 'Wall',
    '(匿名表示 ON)': '(ID Display ON)',
    '(匿名表示 OFF)': '(ID Display OFF)',
}

const translationTablePartial = {
    '新人': '新人',
    '９級': '９級',
    '８級': '８級',
    '７級': '７級',
    '６級': '６級',
    '５級': '５級',
    '４級': '４級',
    '３級': '３級',
    '２級': '２級',
    '１級': '１級',
    '初段': '初段',
    '二段': '二段',
    '三段': '三段',
    '四段': '四段',
    '五段': '五段',
    '六段': '六段',
    '七段': '七段',
    '八段': '八段',
    '九段': '九段',
    '十段': '十段',
    '四般東喰赤': '4, Gen, Est, Opn, Red',
    '四般東喰赤速': '4, Gen, Est, Opn, Red, Fas',
    '四般南喰赤': '4, Gen, Sth, Opn, Red',
    '四般南喰赤速': '4, Gen, Sth, Opn, Red, Fas',
    '三般東喰赤': '3, Gen, Est, Opn, Red',
    '三般東喰赤速': '3, Gen, Est, Opn, Red, Fas',
    '三般南喰赤': '3, Gen, Sth, Opn, Red',
    '三般南喰赤速': '3, Gen, Sth, Opn, Red, Fas',
    '四上東喰赤': '4, Int, Est, Opn, Red',
    '四上東喰赤速': '4, Int, Est, Opn, Red, Fas',
    '四上南喰赤': '4, Int, Sth, Opn, Red',
    '四上南喰赤速': '4, Int, Sth, Opn, Red, Fas',
    '三上東喰赤': '3, Int, Est, Opn, Red',
    '三上東喰赤速': '3, Int, Est, Opn, Red, Fas',
    '三上南喰赤': '3, Int, Sth, Opn, Red',
    '三上南喰赤速': '3, Int, Sth, Opn, Red, Fas',
    '四特東喰赤': '4, Exp, Est, Opn, Red',
    '四特東喰赤速': '4, Exp, Est, Opn, Red, Fas',
    '四特南喰赤': '4, Exp, Sth, Opn, Red',
    '四特南喰赤速': '4, Exp, Sth, Opn, Red, Fas',
    '三特東喰赤': '3, Exp, Est, Opn, Red',
    '三特東喰赤速': '3, Exp, Est, Opn, Red, Fas',
    '三特南喰赤': '3, Exp, Sth, Opn, Red',
    '三特南喰赤速': '3, Exp, Sth, Opn, Red, Fas',
    '四鳳東喰赤': '4, Mas, Est, Opn, Red',
    '四鳳東喰赤速': '4, Mas, Est, Opn, Red, Fas',
    '四鳳南喰赤': '4, Mas, Sth, Opn, Red',
    '四鳳南喰赤速': '4, Mas, Sth, Opn, Red, Fas',
    '三鳳東喰赤': '3, Mas, Est, Opn, Red',
    '三鳳東喰赤速': '3, Mas, Est, Opn, Red, Fas',
    '三鳳南喰赤': '3, Mas, Sth, Opn, Red',
    '三鳳南喰赤速': '3, Mas, Sth, Opn, Red, Fas',
    '四麻上級卓': '4 players, Intermediate',
    '三麻上級卓': '3 players, Intermediate',
    '四麻特上卓': '4 players, Expert',
    '三麻特上卓': '3 players, Expert',
    '四麻雀荘戦': '4 players, Parlor',
    '三麻雀荘戦': '3 players, Parlor',
    '四麻鳳凰卓': '4 players, Master',
    '三麻鳳凰卓': '3 players, Master',
    '巡目': ' Turn',
}

const translationTableTooltip = {
    // Ranks
    '新人': 'rookie',
    '９級': '9kyuu',
    '８級': '8kyuu',
    '７級': '7kyuu',
    '６級': '6kyuu',
    '５級': '5kyuu',
    '４級': '4kyuu',
    '３級': '3kyuu',
    '２級': '2kyuu',
    '１級': '1kyuu',
    '初段': '1dan',
    '二段': '2dan',
    '三段': '3dan',
    '四段': '4dan',
    '五段': '5dan',
    '六段': '6dan',
    '七段': '7dan',
    '八段': '8dan',
    '九段': '9dan',
    '十段': '10dan',
    // Game types
    '四般東喰赤速': '4 players, General, East round, Open tanyao, Red dora, Fast',
    '四般南喰赤': '4 players, General, East + South round, Open tanyao, Red dora',
    '四般南喰赤速': '4 players, General, East + South round, Open tanyao, Red dora, Fast',
    '三般東喰赤': '3 players, General, East round, Open tanyao, Red dora',
    '三般東喰赤速': '3 players, General, East round, Open tanyao, Red dora, Fast',
    '三般南喰赤': '3 players, General, East + South round, Open tanyao, Red dora',
    '三般南喰赤速': '3 players, General, East + South round, Open tanyao, Red dora, Fast',
    '四上東喰赤': '4 players, Intermediate, East round, Open tanyao, Red dora',
    '四上東喰赤速': '4 players, Intermediate, East round, Open tanyao, Red dora, Fast',
    '四上南喰赤': '4 players, Intermediate, East + South round, Open tanyao, Red dora',
    '四上南喰赤速': '4 players, Intermediate, East + South round, Open tanyao, Red dora, Fast',
    '三上東喰赤': '3 players, Intermediate, East round, Open tanyao, Red dora',
    '三上東喰赤速': '3 players, Intermediate, East round, Open tanyao, Red dora, Fast',
    '三上南喰赤': '3 players, Intermediate, East + South round, Open tanyao, Red dora',
    '三上南喰赤速': '3 players, Intermediate, East + South round, Open tanyao, Red dora, Fast',
    '四特東喰赤': '4 players, Expert, East round, Open tanyao, Red dora',
    '四特東喰赤速': '4 players, Expert, East round, Open tanyao, Red dora, Fast',
    '四特南喰赤': '4 players, Expert, East + South round, Open tanyao, Red dora',
    '四特南喰赤速': '4 players, Expert, East + South round, Open tanyao, Red dora, Fast',
    '三特東喰赤': '3 players, Expert, East round, Open tanyao, Red dora',
    '三特東喰赤速': '3 players, Expert, East round, Open tanyao, Red dora, Fast',
    '三特南喰赤': '3 players, Expert, East + South round, Open tanyao, Red dora',
    '三特南喰赤速': '3 players, Expert, East + South round, Open tanyao, Red dora, Fast',
    '四鳳東喰赤': '4 players, Master, East round, Open tanyao, Red dora',
    '四鳳東喰赤速': '4 players, Master, East round, Open tanyao, Red dora, Fast',
    '四鳳南喰赤': '4 players, Master, East + South round, Open tanyao, Red dora',
    '四鳳南喰赤速': '4 players, Master, East + South round, Open tanyao, Red dora, Fast',
    '三鳳東喰赤': '3 players, Master, East round, Open tanyao, Red dora',
    '三鳳東喰赤速': '3 players, Master, East round, Open tanyao, Red dora, Fast',
    '三鳳南喰赤': '3 players, Master, East + South round, Open tanyao, Red dora',
    '三鳳南喰赤速': '3 players, Master, East + South round, Open tanyao, Red dora, Fast',
}

const partialPhrases = Object.keys(translationTablePartial);

const partialMatch = (originalText) => {
    let key;
    for (let i = 0; i < partialPhrases.length; i++) {
        if (originalText.includes(partialPhrases[i])) {
            key = partialPhrases[i];
        }
    }
    return key;
};

let mutationObserver;

const observerSettings = {
    childList: true,
    subtree: true,
}

const onMutate = (mutations) => {
    mutationObserver.disconnect();
    const elements = document.getElementsByTagName('*');

    for (let i = 0; i < elements.length; i++) {
        for (let j = 0; j < elements[i].childNodes.length; j++) {
            if (elements[i].tagName.toLowerCase() === 'button') {
                elements[i].style.overflow = 'hidden';
            }

            let node = elements[i].childNodes[j];
            if (node.nodeType === 3) {
                let originalText = node.nodeValue;
                if (translationTableExact[originalText]) {
                    elements[i].replaceChild(document.createTextNode(translationTableExact[originalText]), node);
                } else if (partialMatch(originalText)) {
                    let partialMatchKey = partialMatch(originalText);
                    if (partialMatchKey) {
                        let newText = originalText.replace(partialMatchKey, translationTablePartial[partialMatchKey]);
                        elements[i].replaceChild(document.createTextNode(newText), node);
                        if (translationTableTooltip[partialMatchKey]) {
                            if (elements[i].tagName.toLowerCase() === 'span') {
                                elements[i].parentElement.style.overflow = 'hidden';
                                elements[i].parentElement.setAttribute('title', translationTableTooltip[partialMatchKey]);
                            } else {
                                elements[i].style.overflow = 'hidden';
                                elements[i].setAttribute('title', translationTableTooltip[partialMatchKey]);
                            }
                        }
                    }
                }
            }
        }
    };
    mutationObserver.observe(document.documentElement, observerSettings);
};

mutationObserver = new MutationObserver(onMutate);

mutationObserver.observe(document.documentElement, observerSettings);
